name: 'private-image-action'
description: 'logs into private registry, builds and pushes docker image'

inputs:

  image:
    description: 'image name'
    required: true
    default: ${{github.event.repository.name}}

  registry:
    description: 'registry hostname'
    required: true
    default: reg.goevolve.org

  user:
    description: 'registry user'
    required: true
    default: github

  password:
    description: 'registry password (for example, take it from secrets.REGISTRY_PASSWORD)'
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{inputs.registry}}
        username: ${{inputs.user}}
        password: ${{inputs.password}}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{inputs.registry}}/${{inputs.image}}
        cache-from: type=registry,ref=${{inputs.registry}}/${{inputs.image}}
        cache-to: type=inline
